/**
 * Generated by scripts/sync-opencode-models.mjs — do not edit by hand.
 * Refresh: `pnpm --dir dsh-auth sync:models`.
 *
 * generatedAt: 2026-09-30T15:19:42.378Z
 * pi-ai: 0.99.1
 * live roster: zen=82 go=43
 * beyond installed catalog: zen=+5 go=+14
 *
 * Shape contract (see src/fresh-models.ts parseSnapshotData):
 * version=1, per route { roster (live chat ids, sorted), entries
 * (allowlisted models.dev metadata for roster ids the installed catalog
 * lacks), fallback (roster ids neither source describes — runtime clones
 * the nearest catalog sibling and flags nothing on the model object;
 * provenance lives here) }, classifiers (live ids pi-ai serves on its
 * classifier path, excluded from the chat merge).
 */
export const OPENCODE_SNAPSHOT = {
  "version": 1,
  "generatedAt": "2026-09-30T15:19:42.378Z",
  "piAiVersion": "0.99.1",
  "sources": {
    "modelsDev": "https://models.dev/api.json",
    "zen": "https://opencode.ai/zen/v1/models",
    "go": "https://opencode.ai/zen/go/v1/models"
  },
  "classifiers": [
    "jev-1.13",
    "jev-1.13-free"
  ],
  "opencode": {
    "roster": [
      "big-pickle",
      "claude-fable-5",
      "claude-fable-5-1",
      "claude-haiku-4-5",
      "claude-opus-4-5",
      "claude-opus-4-6",
      "claude-opus-4-7",
      "claude-opus-4-8",
      "claude-opus-5",
      "claude-opus-5-5",
      "claude-sonnet-4",
      "claude-sonnet-4-5",
      "claude-sonnet-4-6",
      "claude-sonnet-5",
      "claude-sonnet-5-5",
      "deepseek-v4-flash",
      "deepseek-v4-flash-free",
      "deepseek-v4-flash-vision-exp",
      "deepseek-v4-pro",
      "deepseek-v4.1-flash",
      "gemini-3-flash",
      "gemini-3.1-pro",
      "gemini-3.5-flash",
      "gemini-3.5-flash-lite",
      "gemini-3.6-flash",
      "gemini-3.7-flash",
      "gemini-3.8-flash",
      "glm-5",
      "glm-5.1",
      "glm-5.2",
      "glm-5.3",
      "glm-5.3-flash",
      "gpt-5",
      "gpt-5-codex",
      "gpt-5-nano",
      "gpt-5.1",
      "gpt-5.1-codex",
      "gpt-5.1-codex-max",
      "gpt-5.1-codex-mini",
      "gpt-5.2",
      "gpt-5.2-codex",
      "gpt-5.3-codex",
      "gpt-5.3-codex-spark",
      "gpt-5.4",
      "gpt-5.4-mini",
      "gpt-5.4-nano",
      "gpt-5.4-pro",
      "gpt-5.5",
      "gpt-5.5-pro",
      "gpt-5.6-luna",
      "gpt-5.6-sol",
      "gpt-5.6-terra",
      "gpt-6-astra",
      "gpt-6-luna",
      "gpt-6-sol",
      "gpt-6.1-sol",
      "grok-4.5",
      "grok-4.6",
      "grok-4.7",
      "grok-build-0.1",
      "kimi-k2.5",
      "kimi-k2.6",
      "kimi-k2.7-code",
      "kimi-k3",
      "ling-3.0-flash-fin-free",
      "longcat-2.5-preview-free",
      "mimo-v2.5-free",
      "mimo-v2.6-flash-free",
      "minimax-m2.5",
      "minimax-m2.7",
      "minimax-m3",
      "muse-spark-1.2",
      "muse-spark-1.2-contributor-free",
      "muse-spark-1.3",
      "muse-spark-1.3-contributor-free",
      "nemotron-3-ultra-free",
      "nemotron-3.5-lightning-free",
      "qwen3.5-plus",
      "qwen3.6-plus",
      "qwen3.8-flash",
      "qwen3.8-max",
      "space-bunny-free"
    ],
    "entries": {
      "deepseek-v4-flash-free": {
        "id": "deepseek-v4-flash-free",
        "name": "DeepSeek V4 Flash Free",
        "reasoning": true,
        "attachment": false,
        "modalities": {
          "input": [
            "text"
          ]
        },
        "limit": {
          "context": 200000,
          "output": 128000
        },
        "cost": {
          "input": 0,
          "output": 0,
          "cache_read": 0
        },
        "temperature": true,
        "reasoning_options": {
          "effort": [
            "low",
            "high",
            "max"
          ]
        }
      },
      "gpt-5.3-codex-spark": {
        "id": "gpt-5.3-codex-spark",
        "name": "GPT-5.3 Codex Spark",
        "reasoning": true,
        "attachment": false,
        "modalities": {
          "input": [
            "text"
          ]
        },
        "limit": {
          "context": 128000,
          "output": 128000
        },
        "cost": {
          "input": 1.75,
          "output": 14,
          "cache_read": 0.175
        },
        "temperature": false,
        "reasoning_options": {
          "effort": [
            "low",
            "medium",
            "high",
            "xhigh"
          ]
        }
      },
      "gpt-6.1-sol": {
        "id": "gpt-6.1-sol",
        "name": "GPT-6.1 Sol",
        "reasoning": true,
        "attachment": true,
        "modalities": {
          "input": [
            "text",
            "image",
            "pdf"
          ]
        },
        "limit": {
          "context": 1050000,
          "output": 128000
        },
        "cost": {
          "input": 2,
          "output": 10,
          "cache_read": 0.1
        },
        "temperature": false,
        "reasoning_options": {
          "effort": [
            "low",
            "medium",
            "high",
            "xhigh",
            "max"
          ]
        }
      },
      "mimo-v2.5-free": {
        "id": "mimo-v2.5-free",
        "name": "MiMo V2.5 Free",
        "reasoning": true,
        "attachment": true,
        "modalities": {
          "input": [
            "text",
            "image",
            "audio",
            "video"
          ]
        },
        "limit": {
          "context": 200000,
          "output": 32000
        },
        "cost": {
          "input": 0,
          "output": 0,
          "cache_read": 0
        },
        "temperature": true
      },
      "muse-spark-1.2-contributor-free": {
        "id": "muse-spark-1.2-contributor-free",
        "name": "Muse Spark 1.2 Free",
        "reasoning": true,
        "attachment": true,
        "modalities": {
          "input": [
            "text",
            "image",
            "video",
            "pdf",
            "audio"
          ]
        },
        "limit": {
          "context": 1048576,
          "output": 131072
        },
        "cost": {
          "input": 0,
          "output": 0,
          "cache_read": 0
        },
        "temperature": true,
        "reasoning_options": {
          "effort": [
            "minimal",
            "low",
            "medium",
            "high",
            "xhigh"
          ]
        }
      }
    },
    "fallback": []
  },
  "opencode-go": {
    "roster": [
      "deepseek-flash",
      "deepseek-v4-flash",
      "deepseek-v4-flash-vision-exp",
      "deepseek-v4-pro",
      "deepseek-v4.1-flash",
      "glm-5",
      "glm-5.1",
      "glm-5.2",
      "glm-5.3",
      "glm-5.3-flash",
      "gpt-5.6-luna",
      "gpt-6-luna",
      "grok-4.5",
      "grok-4.6",
      "grok-4.7",
      "hy3",
      "hy3-preview",
      "hy4-preview",
      "kimi-k2.5",
      "kimi-k2.6",
      "kimi-k2.7-code",
      "kimi-k3",
      "longcat-2.0",
      "longcat-2.5-preview-free",
      "mimo-v2-omni",
      "mimo-v2-pro",
      "mimo-v2.5",
      "mimo-v2.5-pro",
      "mimo-v2.6-flash",
      "mimo-v2.6-pro",
      "minimax-m2.5",
      "minimax-m2.7",
      "minimax-m3",
      "muse-spark-1.2-contributor",
      "muse-spark-1.3-contributor",
      "omen-alpha",
      "qwen3.5-plus",
      "qwen3.6-plus",
      "qwen3.7-max",
      "qwen3.7-plus",
      "qwen3.8-flash",
      "qwen3.8-max",
      "space-bunny-free"
    ],
    "entries": {
      "glm-5": {
        "id": "glm-5",
        "name": "GLM-5",
        "reasoning": true,
        "attachment": false,
        "modalities": {
          "input": [
            "text"
          ]
        },
        "limit": {
          "context": 204800,
          "output": 131072
        },
        "cost": {
          "input": 1,
          "output": 3.2,
          "cache_read": 0.2
        },
        "temperature": true
      },
      "glm-5.1": {
        "id": "glm-5.1",
        "name": "GLM-5.1",
        "reasoning": true,
        "attachment": false,
        "modalities": {
          "input": [
            "text"
          ]
        },
        "limit": {
          "context": 204800,
          "output": 131072
        },
        "cost": {
          "input": 1.4,
          "output": 4.4,
          "cache_read": 0.26
        },
        "temperature": true
      },
      "grok-4.5": {
        "id": "grok-4.5",
        "name": "Grok 4.5",
        "reasoning": true,
        "attachment": true,
        "modalities": {
          "input": [
            "text",
            "image"
          ]
        },
        "limit": {
          "context": 500000,
          "output": 500000
        },
        "cost": {
          "input": 2,
          "output": 6,
          "cache_read": 0.3
        },
        "temperature": true,
        "reasoning_options": {
          "effort": [
            "low",
            "medium",
            "high"
          ]
        }
      },
      "kimi-k2.5": {
        "id": "kimi-k2.5",
        "name": "Kimi K2.5",
        "reasoning": true,
        "attachment": true,
        "modalities": {
          "input": [
            "text",
            "image",
            "video"
          ]
        },
        "limit": {
          "context": 262144,
          "output": 65536
        },
        "cost": {
          "input": 0.6,
          "output": 3,
          "cache_read": 0.08
        },
        "temperature": true
      },
      "kimi-k2.6": {
        "id": "kimi-k2.6",
        "name": "Kimi K2.6",
        "reasoning": true,
        "attachment": true,
        "modalities": {
          "input": [
            "text",
            "image",
            "video"
          ]
        },
        "limit": {
          "context": 262144,
          "output": 65536
        },
        "cost": {
          "input": 0.95,
          "output": 4,
          "cache_read": 0.16
        },
        "temperature": true
      },
      "minimax-m2.5": {
        "id": "minimax-m2.5",
        "name": "MiniMax-M2.5",
        "reasoning": true,
        "attachment": false,
        "modalities": {
          "input": [
            "text"
          ]
        },
        "limit": {
          "context": 204800,
          "output": 131072
        },
        "cost": {
          "input": 0.3,
          "output": 1.2,
          "cache_read": 0.06
        },
        "temperature": true
      },
      "qwen3.5-plus": {
        "id": "qwen3.5-plus",
        "name": "Qwen3.5 Plus",
        "reasoning": true,
        "attachment": true,
        "modalities": {
          "input": [
            "text",
            "image",
            "video"
          ]
        },
        "limit": {
          "context": 262144,
          "output": 65536
        },
        "cost": {
          "input": 0.2,
          "output": 1.2,
          "cache_read": 0.02
        },
        "temperature": true
      },
      "qwen3.6-plus": {
        "id": "qwen3.6-plus",
        "name": "Qwen3.6 Plus",
        "reasoning": true,
        "attachment": true,
        "modalities": {
          "input": [
            "text",
            "image",
            "video"
          ]
        },
        "limit": {
          "context": 1000000,
          "output": 65536
        },
        "cost": {
          "input": 0.5,
          "output": 3,
          "cache_read": 0.05
        },
        "temperature": true
      },
      "qwen3.7-max": {
        "id": "qwen3.7-max",
        "name": "Qwen3.7 Max",
        "reasoning": true,
        "attachment": false,
        "modalities": {
          "input": [
            "text"
          ]
        },
        "limit": {
          "context": 1000000,
          "output": 65536
        },
        "cost": {
          "input": 2.5,
          "output": 7.5,
          "cache_read": 0.5
        },
        "temperature": true
      }
    },
    "fallback": [
      "deepseek-flash",
      "hy3-preview",
      "mimo-v2-omni",
      "mimo-v2-pro",
      "omen-alpha"
    ]
  }
} as const;
