/**
 * Generated by scripts/sync-opencode-models.mjs — do not edit by hand.
 * Refresh: `pnpm --dir dsh-auth sync:models`.
 *
 * generatedAt: 2026-09-30T16:16:05.230Z
 * pi-ai: 0.99.1
 * live roster: zen=82 go=43
 * beyond installed catalog: zen=+5 go=+14
 *
 * Shape contract (see src/fresh-models.ts parseSnapshotData):
 * version=1, per route { roster (live chat ids, sorted), entries
 * (allowlisted models.dev metadata for all described roster ids), fallback
 * (roster ids models.dev does not describe — runtime clones
 * the nearest catalog sibling and flags nothing on the model object;
 * provenance lives here) }, classifiers (live ids pi-ai serves on its
 * classifier path, excluded from the chat merge).
 */
export const OPENCODE_SNAPSHOT = {
  "version": 1,
  "generatedAt": "2026-09-30T16:16:05.230Z",
  "piAiVersion": "0.99.1",
  "sources": {
    "modelsDev": "https://models.dev/api.json",
    "zen": "https://opencode.ai/zen/v1/models",
    "go": "https://opencode.ai/zen/go/v1/models"
  },
  "classifiers": [
    "jev-1.13",
    "jev-1.13-free"
  ],
  "opencode": {
    "roster": [
      "big-pickle",
      "claude-fable-5",
      "claude-fable-5-1",
      "claude-haiku-4-5",
      "claude-opus-4-5",
      "claude-opus-4-6",
      "claude-opus-4-7",
      "claude-opus-4-8",
      "claude-opus-5",
      "claude-opus-5-5",
      "claude-sonnet-4",
      "claude-sonnet-4-5",
      "claude-sonnet-4-6",
      "claude-sonnet-5",
      "claude-sonnet-5-5",
      "deepseek-v4-flash",
      "deepseek-v4-flash-free",
      "deepseek-v4-flash-vision-exp",
      "deepseek-v4-pro",
      "deepseek-v4.1-flash",
      "gemini-3-flash",
      "gemini-3.1-pro",
      "gemini-3.5-flash",
      "gemini-3.5-flash-lite",
      "gemini-3.6-flash",
      "gemini-3.7-flash",
      "gemini-3.8-flash",
      "glm-5",
      "glm-5.1",
      "glm-5.2",
      "glm-5.3",
      "glm-5.3-flash",
      "gpt-5",
      "gpt-5-codex",
      "gpt-5-nano",
      "gpt-5.1",
      "gpt-5.1-codex",
      "gpt-5.1-codex-max",
      "gpt-5.1-codex-mini",
      "gpt-5.2",
      "gpt-5.2-codex",
      "gpt-5.3-codex",
      "gpt-5.3-codex-spark",
      "gpt-5.4",
      "gpt-5.4-mini",
      "gpt-5.4-nano",
      "gpt-5.4-pro",
      "gpt-5.5",
      "gpt-5.5-pro",
      "gpt-5.6-luna",
      "gpt-5.6-sol",
      "gpt-5.6-terra",
      "gpt-6-astra",
      "gpt-6-luna",
      "gpt-6-sol",
      "gpt-6.1-sol",
      "grok-4.5",
      "grok-4.6",
      "grok-4.7",
      "grok-build-0.1",
      "kimi-k2.5",
      "kimi-k2.6",
      "kimi-k2.7-code",
      "kimi-k3",
      "ling-3.0-flash-fin-free",
      "longcat-2.5-preview-free",
      "mimo-v2.5-free",
      "mimo-v2.6-flash-free",
      "minimax-m2.5",
      "minimax-m2.7",
      "minimax-m3",
      "muse-spark-1.2",
      "muse-spark-1.2-contributor-free",
      "muse-spark-1.3",
      "muse-spark-1.3-contributor-free",
      "nemotron-3-ultra-free",
      "nemotron-3.5-lightning-free",
      "qwen3.5-plus",
      "qwen3.6-plus",
      "qwen3.8-flash",
      "qwen3.8-max",
      "space-bunny-free"
    ],
    "entries": {
      "big-pickle": {
        "id": "big-pickle",
        "name": "Big Pickle",
        "reasoning": true,
        "attachment": false,
        "modalities": {
          "input": [
            "text"
          ]
        },
        "limit": {
          "context": 200000,
          "output": 32000
        },
        "cost": {
          "input": 0,
          "output": 0,
          "cache_read": 0
        },
        "temperature": true
      },
      "claude-fable-5": {
        "id": "claude-fable-5",
        "name": "Claude Fable 5",
        "reasoning": true,
        "attachment": true,
        "modalities": {
          "input": [
            "text",
            "image",
            "pdf"
          ]
        },
        "limit": {
          "context": 1000000,
          "output": 128000
        },
        "cost": {
          "input": 10,
          "output": 50,
          "cache_read": 1
        },
        "temperature": false,
        "reasoning_options": {
          "effort": [
            "low",
            "medium",
            "high",
            "xhigh",
            "max"
          ]
        }
      },
      "claude-fable-5-1": {
        "id": "claude-fable-5-1",
        "name": "Claude Fable 5.1",
        "reasoning": true,
        "attachment": true,
        "modalities": {
          "input": [
            "text",
            "image",
            "pdf"
          ]
        },
        "limit": {
          "context": 1000000,
          "output": 128000
        },
        "cost": {
          "input": 10,
          "output": 50,
          "cache_read": 0.25
        },
        "temperature": false,
        "reasoning_options": {
          "effort": [
            "low",
            "medium",
            "high",
            "xhigh",
            "max"
          ]
        }
      },
      "claude-haiku-4-5": {
        "id": "claude-haiku-4-5",
        "name": "Claude Haiku 4.5",
        "reasoning": true,
        "attachment": true,
        "modalities": {
          "input": [
            "text",
            "image",
            "pdf"
          ]
        },
        "limit": {
          "context": 200000,
          "output": 64000
        },
        "cost": {
          "input": 1,
          "output": 5,
          "cache_read": 0.1
        },
        "temperature": true
      },
      "claude-opus-4-5": {
        "id": "claude-opus-4-5",
        "name": "Claude Opus 4.5",
        "reasoning": true,
        "attachment": true,
        "modalities": {
          "input": [
            "text",
            "image",
            "pdf"
          ]
        },
        "limit": {
          "context": 200000,
          "output": 64000
        },
        "cost": {
          "input": 5,
          "output": 25,
          "cache_read": 0.5
        },
        "temperature": true,
        "reasoning_options": {
          "effort": [
            "low",
            "medium",
            "high"
          ]
        }
      },
      "claude-opus-4-6": {
        "id": "claude-opus-4-6",
        "name": "Claude Opus 4.6",
        "reasoning": true,
        "attachment": true,
        "modalities": {
          "input": [
            "text",
            "image",
            "pdf"
          ]
        },
        "limit": {
          "context": 1000000,
          "output": 128000
        },
        "cost": {
          "input": 5,
          "output": 25,
          "cache_read": 0.5
        },
        "temperature": true,
        "reasoning_options": {
          "effort": [
            "low",
            "medium",
            "high",
            "max"
          ]
        }
      },
      "claude-opus-4-7": {
        "id": "claude-opus-4-7",
        "name": "Claude Opus 4.7",
        "reasoning": true,
        "attachment": true,
        "modalities": {
          "input": [
            "text",
            "image",
            "pdf"
          ]
        },
        "limit": {
          "context": 1000000,
          "output": 128000
        },
        "cost": {
          "input": 5,
          "output": 25,
          "cache_read": 0.5
        },
        "temperature": false,
        "reasoning_options": {
          "effort": [
            "low",
            "medium",
            "high",
            "xhigh",
            "max"
          ]
        }
      },
      "claude-opus-4-8": {
        "id": "claude-opus-4-8",
        "name": "Claude Opus 4.8",
        "reasoning": true,
        "attachment": true,
        "modalities": {
          "input": [
            "text",
            "image",
            "pdf"
          ]
        },
        "limit": {
          "context": 1000000,
          "output": 128000
        },
        "cost": {
          "input": 5,
          "output": 25,
          "cache_read": 0.5
        },
        "temperature": false,
        "reasoning_options": {
          "effort": [
            "low",
            "medium",
            "high",
            "xhigh",
            "max"
          ]
        }
      },
      "claude-opus-5": {
        "id": "claude-opus-5",
        "name": "Claude Opus 5",
        "reasoning": true,
        "attachment": true,
        "modalities": {
          "input": [
            "text",
            "image",
            "pdf"
          ]
        },
        "limit": {
          "context": 1000000,
          "output": 128000
        },
        "cost": {
          "input": 5,
          "output": 25,
          "cache_read": 0.5
        },
        "temperature": false,
        "reasoning_options": {
          "effort": [
            "low",
            "medium",
            "high",
            "xhigh",
            "max"
          ]
        }
      },
      "claude-opus-5-5": {
        "id": "claude-opus-5-5",
        "name": "Claude Opus 5.5",
        "reasoning": true,
        "attachment": true,
        "modalities": {
          "input": [
            "text",
            "image",
            "pdf"
          ]
        },
        "limit": {
          "context": 1000000,
          "output": 128000
        },
        "cost": {
          "input": 4,
          "output": 20,
          "cache_read": 0.2
        },
        "temperature": false,
        "reasoning_options": {
          "effort": [
            "low",
            "medium",
            "high",
            "xhigh",
            "max"
          ]
        }
      },
      "claude-sonnet-4": {
        "id": "claude-sonnet-4",
        "name": "Claude Sonnet 4",
        "reasoning": true,
        "attachment": true,
        "modalities": {
          "input": [
            "text",
            "image",
            "pdf"
          ]
        },
        "limit": {
          "context": 1000000,
          "output": 64000
        },
        "cost": {
          "input": 3,
          "output": 15,
          "cache_read": 0.3
        },
        "temperature": true
      },
      "claude-sonnet-4-5": {
        "id": "claude-sonnet-4-5",
        "name": "Claude Sonnet 4.5",
        "reasoning": true,
        "attachment": true,
        "modalities": {
          "input": [
            "text",
            "image",
            "pdf"
          ]
        },
        "limit": {
          "context": 1000000,
          "output": 64000
        },
        "cost": {
          "input": 3,
          "output": 15,
          "cache_read": 0.3
        },
        "temperature": true
      },
      "claude-sonnet-4-6": {
        "id": "claude-sonnet-4-6",
        "name": "Claude Sonnet 4.6",
        "reasoning": true,
        "attachment": true,
        "modalities": {
          "input": [
            "text",
            "image",
            "pdf"
          ]
        },
        "limit": {
          "context": 1000000,
          "output": 64000
        },
        "cost": {
          "input": 3,
          "output": 15,
          "cache_read": 0.3
        },
        "temperature": true,
        "reasoning_options": {
          "effort": [
            "low",
            "medium",
            "high",
            "max"
          ]
        }
      },
      "claude-sonnet-5": {
        "id": "claude-sonnet-5",
        "name": "Claude Sonnet 5",
        "reasoning": true,
        "attachment": true,
        "modalities": {
          "input": [
            "text",
            "image",
            "pdf"
          ]
        },
        "limit": {
          "context": 1000000,
          "output": 128000
        },
        "cost": {
          "input": 2,
          "output": 10,
          "cache_read": 0.2
        },
        "temperature": false,
        "reasoning_options": {
          "effort": [
            "low",
            "medium",
            "high",
            "xhigh",
            "max"
          ]
        }
      },
      "claude-sonnet-5-5": {
        "id": "claude-sonnet-5-5",
        "name": "Claude Sonnet 5.5",
        "reasoning": true,
        "attachment": true,
        "modalities": {
          "input": [
            "text",
            "image",
            "pdf"
          ]
        },
        "limit": {
          "context": 1000000,
          "output": 128000
        },
        "cost": {
          "input": 2,
          "output": 10,
          "cache_read": 0.2
        },
        "temperature": false,
        "reasoning_options": {
          "effort": [
            "low",
            "medium",
            "high",
            "xhigh",
            "max"
          ]
        }
      },
      "deepseek-v4-flash": {
        "id": "deepseek-v4-flash",
        "name": "DeepSeek V4 Flash",
        "reasoning": true,
        "attachment": false,
        "modalities": {
          "input": [
            "text"
          ]
        },
        "limit": {
          "context": 1000000,
          "output": 384000
        },
        "cost": {
          "input": 0.14,
          "output": 0.28,
          "cache_read": 0.028
        },
        "temperature": true,
        "reasoning_options": {
          "effort": [
            "low",
            "high",
            "max"
          ]
        }
      },
      "deepseek-v4-flash-free": {
        "id": "deepseek-v4-flash-free",
        "name": "DeepSeek V4 Flash Free",
        "reasoning": true,
        "attachment": false,
        "modalities": {
          "input": [
            "text"
          ]
        },
        "limit": {
          "context": 200000,
          "output": 128000
        },
        "cost": {
          "input": 0,
          "output": 0,
          "cache_read": 0
        },
        "temperature": true,
        "reasoning_options": {
          "effort": [
            "low",
            "high",
            "max"
          ]
        }
      },
      "deepseek-v4-flash-vision-exp": {
        "id": "deepseek-v4-flash-vision-exp",
        "name": "DeepSeek V4 Flash Vision Exp",
        "reasoning": true,
        "attachment": true,
        "modalities": {
          "input": [
            "text",
            "image"
          ]
        },
        "limit": {
          "context": 1000000,
          "output": 384000
        },
        "cost": {
          "input": 0.14,
          "output": 0.28,
          "cache_read": 0.028
        },
        "temperature": true,
        "reasoning_options": {
          "effort": [
            "low",
            "high",
            "max"
          ]
        }
      },
      "deepseek-v4-pro": {
        "id": "deepseek-v4-pro",
        "name": "DeepSeek V4 Pro",
        "reasoning": true,
        "attachment": false,
        "modalities": {
          "input": [
            "text"
          ]
        },
        "limit": {
          "context": 1000000,
          "output": 384000
        },
        "cost": {
          "input": 1.74,
          "output": 3.84,
          "cache_read": 0.145
        },
        "temperature": true,
        "reasoning_options": {
          "effort": [
            "high",
            "max"
          ]
        }
      },
      "deepseek-v4.1-flash": {
        "id": "deepseek-v4.1-flash",
        "name": "DeepSeek V4.1 Flash",
        "reasoning": true,
        "attachment": true,
        "modalities": {
          "input": [
            "text",
            "image"
          ]
        },
        "limit": {
          "context": 1000000,
          "output": 384000
        },
        "cost": {
          "input": 0.3,
          "output": 1.2,
          "cache_read": 0.006
        },
        "temperature": true,
        "reasoning_options": {
          "effort": [
            "low",
            "high",
            "max"
          ]
        }
      },
      "gemini-3-flash": {
        "id": "gemini-3-flash",
        "name": "Gemini 3 Flash",
        "reasoning": true,
        "attachment": true,
        "modalities": {
          "input": [
            "text",
            "image",
            "video",
            "audio",
            "pdf"
          ]
        },
        "limit": {
          "context": 1048576,
          "output": 65536
        },
        "cost": {
          "input": 0.5,
          "output": 3,
          "cache_read": 0.05
        },
        "temperature": true,
        "reasoning_options": {
          "effort": [
            "minimal",
            "low",
            "medium",
            "high"
          ]
        }
      },
      "gemini-3.1-pro": {
        "id": "gemini-3.1-pro",
        "name": "Gemini 3.1 Pro Preview",
        "reasoning": true,
        "attachment": true,
        "modalities": {
          "input": [
            "text",
            "image",
            "video",
            "audio",
            "pdf"
          ]
        },
        "limit": {
          "context": 1048576,
          "output": 65536
        },
        "cost": {
          "input": 2,
          "output": 12,
          "cache_read": 0.2
        },
        "temperature": true,
        "reasoning_options": {
          "effort": [
            "low",
            "medium",
            "high"
          ]
        }
      },
      "gemini-3.5-flash": {
        "id": "gemini-3.5-flash",
        "name": "Gemini 3.5 Flash",
        "reasoning": true,
        "attachment": true,
        "modalities": {
          "input": [
            "text",
            "image",
            "video",
            "audio",
            "pdf"
          ]
        },
        "limit": {
          "context": 1048576,
          "output": 65536
        },
        "cost": {
          "input": 1.5,
          "output": 9,
          "cache_read": 0.15
        },
        "temperature": true,
        "reasoning_options": {
          "effort": [
            "minimal",
            "low",
            "medium",
            "high"
          ]
        }
      },
      "gemini-3.5-flash-lite": {
        "id": "gemini-3.5-flash-lite",
        "name": "Gemini 3.5 Flash Lite",
        "reasoning": true,
        "attachment": true,
        "modalities": {
          "input": [
            "text",
            "image",
            "video",
            "audio",
            "pdf"
          ]
        },
        "limit": {
          "context": 1048576,
          "output": 65536
        },
        "cost": {
          "input": 0.3,
          "output": 2.5,
          "cache_read": 0.03
        },
        "temperature": true,
        "reasoning_options": {
          "effort": [
            "minimal",
            "low",
            "medium",
            "high"
          ]
        }
      },
      "gemini-3.6-flash": {
        "id": "gemini-3.6-flash",
        "name": "Gemini 3.6 Flash",
        "reasoning": true,
        "attachment": true,
        "modalities": {
          "input": [
            "text",
            "image",
            "video",
            "audio",
            "pdf"
          ]
        },
        "limit": {
          "context": 1048576,
          "output": 65536
        },
        "cost": {
          "input": 1.5,
          "output": 7.5,
          "cache_read": 0.15
        },
        "temperature": true,
        "reasoning_options": {
          "effort": [
            "minimal",
            "low",
            "medium",
            "high"
          ]
        }
      },
      "gemini-3.7-flash": {
        "id": "gemini-3.7-flash",
        "name": "Gemini 3.7 Flash",
        "reasoning": true,
        "attachment": true,
        "modalities": {
          "input": [
            "text",
            "image",
            "video",
            "audio",
            "pdf"
          ]
        },
        "limit": {
          "context": 1048576,
          "output": 65536
        },
        "cost": {
          "input": 1.5,
          "output": 7.5,
          "cache_read": 0.15
        },
        "temperature": true,
        "reasoning_options": {
          "effort": [
            "low",
            "medium",
            "high"
          ]
        }
      },
      "gemini-3.8-flash": {
        "id": "gemini-3.8-flash",
        "name": "Gemini 3.8 Flash",
        "reasoning": true,
        "attachment": true,
        "modalities": {
          "input": [
            "text",
            "image",
            "video",
            "audio",
            "pdf"
          ]
        },
        "limit": {
          "context": 1048576,
          "output": 65536
        },
        "cost": {
          "input": 1.5,
          "output": 7.5,
          "cache_read": 0.15
        },
        "temperature": true,
        "reasoning_options": {
          "effort": [
            "low",
            "medium",
            "high"
          ]
        }
      },
      "glm-5": {
        "id": "glm-5",
        "name": "GLM-5",
        "reasoning": true,
        "attachment": false,
        "modalities": {
          "input": [
            "text"
          ]
        },
        "limit": {
          "context": 204800,
          "output": 131072
        },
        "cost": {
          "input": 1,
          "output": 3.2,
          "cache_read": 0.2
        },
        "temperature": true
      },
      "glm-5.1": {
        "id": "glm-5.1",
        "name": "GLM-5.1",
        "reasoning": true,
        "attachment": false,
        "modalities": {
          "input": [
            "text"
          ]
        },
        "limit": {
          "context": 204800,
          "output": 131072
        },
        "cost": {
          "input": 1.4,
          "output": 4.4,
          "cache_read": 0.26
        },
        "temperature": true
      },
      "glm-5.2": {
        "id": "glm-5.2",
        "name": "GLM-5.2",
        "reasoning": true,
        "attachment": false,
        "modalities": {
          "input": [
            "text"
          ]
        },
        "limit": {
          "context": 1000000,
          "output": 131072
        },
        "cost": {
          "input": 1.4,
          "output": 4.4,
          "cache_read": 0.26
        },
        "temperature": true,
        "reasoning_options": {
          "effort": [
            "high",
            "max"
          ]
        }
      },
      "glm-5.3": {
        "id": "glm-5.3",
        "name": "GLM-5.3",
        "reasoning": true,
        "attachment": false,
        "modalities": {
          "input": [
            "text"
          ]
        },
        "limit": {
          "context": 1000000,
          "output": 131072
        },
        "cost": {
          "input": 1.4,
          "output": 4.4,
          "cache_read": 0.26
        },
        "temperature": true,
        "reasoning_options": {
          "effort": [
            "low",
            "high",
            "max"
          ]
        }
      },
      "glm-5.3-flash": {
        "id": "glm-5.3-flash",
        "name": "GLM-5.3-Flash",
        "reasoning": true,
        "attachment": true,
        "modalities": {
          "input": [
            "text",
            "image",
            "video",
            "pdf"
          ]
        },
        "limit": {
          "context": 1000000,
          "output": 131072
        },
        "cost": {
          "input": 0.15,
          "output": 0.5,
          "cache_read": 0.03
        },
        "temperature": true,
        "reasoning_options": {
          "effort": [
            "low",
            "high",
            "max"
          ]
        }
      },
      "gpt-5": {
        "id": "gpt-5",
        "name": "GPT-5",
        "reasoning": true,
        "attachment": true,
        "modalities": {
          "input": [
            "text",
            "image"
          ]
        },
        "limit": {
          "context": 400000,
          "output": 128000
        },
        "cost": {
          "input": 1.07,
          "output": 8.5,
          "cache_read": 0.107
        },
        "temperature": false,
        "reasoning_options": {
          "effort": [
            "minimal",
            "low",
            "medium",
            "high"
          ]
        }
      },
      "gpt-5-codex": {
        "id": "gpt-5-codex",
        "name": "GPT-5 Codex",
        "reasoning": true,
        "attachment": true,
        "modalities": {
          "input": [
            "text",
            "image"
          ]
        },
        "limit": {
          "context": 400000,
          "output": 128000
        },
        "cost": {
          "input": 1.07,
          "output": 8.5,
          "cache_read": 0.107
        },
        "temperature": false,
        "reasoning_options": {
          "effort": [
            "low",
            "medium",
            "high"
          ]
        }
      },
      "gpt-5-nano": {
        "id": "gpt-5-nano",
        "name": "GPT-5 Nano",
        "reasoning": true,
        "attachment": true,
        "modalities": {
          "input": [
            "text",
            "image"
          ]
        },
        "limit": {
          "context": 400000,
          "output": 128000
        },
        "cost": {
          "input": 0.05,
          "output": 0.4,
          "cache_read": 0.005
        },
        "temperature": false,
        "reasoning_options": {
          "effort": [
            "minimal",
            "low",
            "medium",
            "high"
          ]
        }
      },
      "gpt-5.1": {
        "id": "gpt-5.1",
        "name": "GPT-5.1",
        "reasoning": true,
        "attachment": true,
        "modalities": {
          "input": [
            "text",
            "image"
          ]
        },
        "limit": {
          "context": 400000,
          "output": 128000
        },
        "cost": {
          "input": 1.07,
          "output": 8.5,
          "cache_read": 0.107
        },
        "temperature": false,
        "reasoning_options": {
          "effort": [
            "none",
            "low",
            "medium",
            "high"
          ]
        }
      },
      "gpt-5.1-codex": {
        "id": "gpt-5.1-codex",
        "name": "GPT-5.1 Codex",
        "reasoning": true,
        "attachment": true,
        "modalities": {
          "input": [
            "text",
            "image"
          ]
        },
        "limit": {
          "context": 400000,
          "output": 128000
        },
        "cost": {
          "input": 1.07,
          "output": 8.5,
          "cache_read": 0.107
        },
        "temperature": false,
        "reasoning_options": {
          "effort": [
            "low",
            "medium",
            "high"
          ]
        }
      },
      "gpt-5.1-codex-max": {
        "id": "gpt-5.1-codex-max",
        "name": "GPT-5.1 Codex Max",
        "reasoning": true,
        "attachment": true,
        "modalities": {
          "input": [
            "text",
            "image"
          ]
        },
        "limit": {
          "context": 400000,
          "output": 128000
        },
        "cost": {
          "input": 1.25,
          "output": 10,
          "cache_read": 0.125
        },
        "temperature": false,
        "reasoning_options": {
          "effort": [
            "low",
            "medium",
            "high",
            "xhigh"
          ]
        }
      },
      "gpt-5.1-codex-mini": {
        "id": "gpt-5.1-codex-mini",
        "name": "GPT-5.1 Codex Mini",
        "reasoning": true,
        "attachment": true,
        "modalities": {
          "input": [
            "text",
            "image"
          ]
        },
        "limit": {
          "context": 400000,
          "output": 128000
        },
        "cost": {
          "input": 0.25,
          "output": 2,
          "cache_read": 0.025
        },
        "temperature": false,
        "reasoning_options": {
          "effort": [
            "low",
            "medium",
            "high"
          ]
        }
      },
      "gpt-5.2": {
        "id": "gpt-5.2",
        "name": "GPT-5.2",
        "reasoning": true,
        "attachment": true,
        "modalities": {
          "input": [
            "text",
            "image"
          ]
        },
        "limit": {
          "context": 400000,
          "output": 128000
        },
        "cost": {
          "input": 1.75,
          "output": 14,
          "cache_read": 0.175
        },
        "temperature": false,
        "reasoning_options": {
          "effort": [
            "none",
            "low",
            "medium",
            "high",
            "xhigh"
          ]
        }
      },
      "gpt-5.2-codex": {
        "id": "gpt-5.2-codex",
        "name": "GPT-5.2 Codex",
        "reasoning": true,
        "attachment": true,
        "modalities": {
          "input": [
            "text",
            "image",
            "pdf"
          ]
        },
        "limit": {
          "context": 400000,
          "output": 128000
        },
        "cost": {
          "input": 1.75,
          "output": 14,
          "cache_read": 0.175
        },
        "temperature": false,
        "reasoning_options": {
          "effort": [
            "low",
            "medium",
            "high",
            "xhigh"
          ]
        }
      },
      "gpt-5.3-codex": {
        "id": "gpt-5.3-codex",
        "name": "GPT-5.3 Codex",
        "reasoning": true,
        "attachment": true,
        "modalities": {
          "input": [
            "text",
            "image",
            "pdf"
          ]
        },
        "limit": {
          "context": 400000,
          "output": 128000
        },
        "cost": {
          "input": 1.75,
          "output": 14,
          "cache_read": 0.175
        },
        "temperature": false,
        "reasoning_options": {
          "effort": [
            "none",
            "low",
            "medium",
            "high",
            "xhigh"
          ]
        }
      },
      "gpt-5.3-codex-spark": {
        "id": "gpt-5.3-codex-spark",
        "name": "GPT-5.3 Codex Spark",
        "reasoning": true,
        "attachment": false,
        "modalities": {
          "input": [
            "text"
          ]
        },
        "limit": {
          "context": 128000,
          "output": 128000
        },
        "cost": {
          "input": 1.75,
          "output": 14,
          "cache_read": 0.175
        },
        "temperature": false,
        "reasoning_options": {
          "effort": [
            "low",
            "medium",
            "high",
            "xhigh"
          ]
        }
      },
      "gpt-5.4": {
        "id": "gpt-5.4",
        "name": "GPT-5.4",
        "reasoning": true,
        "attachment": true,
        "modalities": {
          "input": [
            "text",
            "image",
            "pdf"
          ]
        },
        "limit": {
          "context": 1050000,
          "output": 128000
        },
        "cost": {
          "input": 2.5,
          "output": 15,
          "cache_read": 0.25
        },
        "temperature": true,
        "reasoning_options": {
          "effort": [
            "none",
            "low",
            "medium",
            "high",
            "xhigh"
          ]
        }
      },
      "gpt-5.4-mini": {
        "id": "gpt-5.4-mini",
        "name": "GPT-5.4 Mini",
        "reasoning": true,
        "attachment": true,
        "modalities": {
          "input": [
            "text",
            "image",
            "pdf"
          ]
        },
        "limit": {
          "context": 400000,
          "output": 128000
        },
        "cost": {
          "input": 0.75,
          "output": 4.5,
          "cache_read": 0.075
        },
        "temperature": false,
        "reasoning_options": {
          "effort": [
            "none",
            "low",
            "medium",
            "high",
            "xhigh"
          ]
        }
      },
      "gpt-5.4-nano": {
        "id": "gpt-5.4-nano",
        "name": "GPT-5.4 Nano",
        "reasoning": true,
        "attachment": true,
        "modalities": {
          "input": [
            "text",
            "image",
            "pdf"
          ]
        },
        "limit": {
          "context": 400000,
          "output": 128000
        },
        "cost": {
          "input": 0.2,
          "output": 1.25,
          "cache_read": 0.02
        },
        "temperature": false,
        "reasoning_options": {
          "effort": [
            "none",
            "low",
            "medium",
            "high",
            "xhigh"
          ]
        }
      },
      "gpt-5.4-pro": {
        "id": "gpt-5.4-pro",
        "name": "GPT-5.4 Pro",
        "reasoning": true,
        "attachment": true,
        "modalities": {
          "input": [
            "text",
            "image",
            "pdf"
          ]
        },
        "limit": {
          "context": 1050000,
          "output": 128000
        },
        "cost": {
          "input": 30,
          "output": 180,
          "cache_read": 30
        },
        "temperature": false,
        "reasoning_options": {
          "effort": [
            "medium",
            "high",
            "xhigh"
          ]
        }
      },
      "gpt-5.5": {
        "id": "gpt-5.5",
        "name": "GPT-5.5",
        "reasoning": true,
        "attachment": true,
        "modalities": {
          "input": [
            "text",
            "image",
            "pdf"
          ]
        },
        "limit": {
          "context": 1050000,
          "output": 128000
        },
        "cost": {
          "input": 5,
          "output": 30,
          "cache_read": 0.5
        },
        "temperature": false,
        "reasoning_options": {
          "effort": [
            "none",
            "low",
            "medium",
            "high",
            "xhigh"
          ]
        }
      },
      "gpt-5.5-pro": {
        "id": "gpt-5.5-pro",
        "name": "GPT-5.5 Pro",
        "reasoning": true,
        "attachment": true,
        "modalities": {
          "input": [
            "text",
            "image",
            "pdf"
          ]
        },
        "limit": {
          "context": 1050000,
          "output": 128000
        },
        "cost": {
          "input": 30,
          "output": 180,
          "cache_read": 30
        },
        "temperature": false,
        "reasoning_options": {
          "effort": [
            "medium",
            "high",
            "xhigh"
          ]
        }
      },
      "gpt-5.6-luna": {
        "id": "gpt-5.6-luna",
        "name": "GPT-5.6 Luna",
        "reasoning": true,
        "attachment": true,
        "modalities": {
          "input": [
            "text",
            "image",
            "pdf"
          ]
        },
        "limit": {
          "context": 1050000,
          "output": 128000
        },
        "cost": {
          "input": 0.2,
          "output": 1.2,
          "cache_read": 0.02
        },
        "temperature": false,
        "reasoning_options": {
          "effort": [
            "none",
            "low",
            "medium",
            "high",
            "xhigh",
            "max"
          ]
        }
      },
      "gpt-5.6-sol": {
        "id": "gpt-5.6-sol",
        "name": "GPT-5.6 Sol",
        "reasoning": true,
        "attachment": true,
        "modalities": {
          "input": [
            "text",
            "image",
            "pdf"
          ]
        },
        "limit": {
          "context": 1050000,
          "output": 128000
        },
        "cost": {
          "input": 4,
          "output": 20,
          "cache_read": 0.4
        },
        "temperature": false,
        "reasoning_options": {
          "effort": [
            "none",
            "low",
            "medium",
            "high",
            "xhigh",
            "max"
          ]
        }
      },
      "gpt-5.6-terra": {
        "id": "gpt-5.6-terra",
        "name": "GPT-5.6 Terra",
        "reasoning": true,
        "attachment": true,
        "modalities": {
          "input": [
            "text",
            "image",
            "pdf"
          ]
        },
        "limit": {
          "context": 1050000,
          "output": 128000
        },
        "cost": {
          "input": 2.5,
          "output": 15,
          "cache_read": 0.25
        },
        "temperature": false,
        "reasoning_options": {
          "effort": [
            "none",
            "low",
            "medium",
            "high",
            "xhigh",
            "max"
          ]
        }
      },
      "gpt-6-astra": {
        "id": "gpt-6-astra",
        "name": "GPT-6 Astra",
        "reasoning": true,
        "attachment": true,
        "modalities": {
          "input": [
            "text",
            "image",
            "pdf"
          ]
        },
        "limit": {
          "context": 1050000,
          "output": 128000
        },
        "cost": {
          "input": 10,
          "output": 50,
          "cache_read": 1
        },
        "temperature": false,
        "reasoning_options": {
          "effort": [
            "low",
            "medium",
            "high",
            "xhigh",
            "max"
          ]
        }
      },
      "gpt-6-luna": {
        "id": "gpt-6-luna",
        "name": "GPT-6 Luna",
        "reasoning": true,
        "attachment": true,
        "modalities": {
          "input": [
            "text",
            "image",
            "pdf"
          ]
        },
        "limit": {
          "context": 1050000,
          "output": 128000
        },
        "cost": {
          "input": 0.1,
          "output": 0.5,
          "cache_read": 0.01
        },
        "temperature": false,
        "reasoning_options": {
          "effort": [
            "none",
            "low",
            "medium",
            "high",
            "xhigh",
            "max"
          ]
        }
      },
      "gpt-6-sol": {
        "id": "gpt-6-sol",
        "name": "GPT-6 Sol",
        "reasoning": true,
        "attachment": true,
        "modalities": {
          "input": [
            "text",
            "image",
            "pdf"
          ]
        },
        "limit": {
          "context": 1050000,
          "output": 128000
        },
        "cost": {
          "input": 2,
          "output": 10,
          "cache_read": 0.2
        },
        "temperature": false,
        "reasoning_options": {
          "effort": [
            "none",
            "low",
            "medium",
            "high",
            "xhigh",
            "max"
          ]
        }
      },
      "gpt-6.1-sol": {
        "id": "gpt-6.1-sol",
        "name": "GPT-6.1 Sol",
        "reasoning": true,
        "attachment": true,
        "modalities": {
          "input": [
            "text",
            "image",
            "pdf"
          ]
        },
        "limit": {
          "context": 1050000,
          "output": 128000
        },
        "cost": {
          "input": 2,
          "output": 10,
          "cache_read": 0.1
        },
        "temperature": false,
        "reasoning_options": {
          "effort": [
            "low",
            "medium",
            "high",
            "xhigh",
            "max"
          ]
        }
      },
      "grok-4.5": {
        "id": "grok-4.5",
        "name": "Grok 4.5",
        "reasoning": true,
        "attachment": true,
        "modalities": {
          "input": [
            "text",
            "image"
          ]
        },
        "limit": {
          "context": 500000,
          "output": 500000
        },
        "cost": {
          "input": 2,
          "output": 6,
          "cache_read": 0.3
        },
        "temperature": true,
        "reasoning_options": {
          "effort": [
            "low",
            "medium",
            "high"
          ]
        }
      },
      "grok-4.6": {
        "id": "grok-4.6",
        "name": "Grok 4.6",
        "reasoning": true,
        "attachment": true,
        "modalities": {
          "input": [
            "text",
            "image"
          ]
        },
        "limit": {
          "context": 500000,
          "output": 500000
        },
        "cost": {
          "input": 2,
          "output": 6,
          "cache_read": 0.5
        },
        "temperature": true,
        "reasoning_options": {
          "effort": [
            "low",
            "medium",
            "high",
            "xhigh"
          ]
        }
      },
      "grok-4.7": {
        "id": "grok-4.7",
        "name": "Grok 4.7",
        "reasoning": true,
        "attachment": true,
        "modalities": {
          "input": [
            "text",
            "image",
            "pdf"
          ]
        },
        "limit": {
          "context": 500000,
          "output": 500000
        },
        "cost": {
          "input": 2,
          "output": 6,
          "cache_read": 0.5
        },
        "temperature": true,
        "reasoning_options": {
          "effort": [
            "low",
            "medium",
            "high",
            "xhigh"
          ]
        }
      },
      "grok-build-0.1": {
        "id": "grok-build-0.1",
        "name": "Grok Build 0.1",
        "reasoning": true,
        "attachment": true,
        "modalities": {
          "input": [
            "text",
            "image",
            "pdf"
          ]
        },
        "limit": {
          "context": 256000,
          "output": 256000
        },
        "cost": {
          "input": 1,
          "output": 2,
          "cache_read": 0.2
        },
        "temperature": true
      },
      "kimi-k2.5": {
        "id": "kimi-k2.5",
        "name": "Kimi K2.5",
        "reasoning": true,
        "attachment": true,
        "modalities": {
          "input": [
            "text",
            "image",
            "video"
          ]
        },
        "limit": {
          "context": 262144,
          "output": 65536
        },
        "cost": {
          "input": 0.6,
          "output": 3,
          "cache_read": 0.08
        },
        "temperature": true
      },
      "kimi-k2.6": {
        "id": "kimi-k2.6",
        "name": "Kimi K2.6",
        "reasoning": true,
        "attachment": true,
        "modalities": {
          "input": [
            "text",
            "image",
            "video"
          ]
        },
        "limit": {
          "context": 262144,
          "output": 65536
        },
        "cost": {
          "input": 0.95,
          "output": 4,
          "cache_read": 0.16
        },
        "temperature": true
      },
      "kimi-k2.7-code": {
        "id": "kimi-k2.7-code",
        "name": "Kimi K2.7 Code",
        "reasoning": true,
        "attachment": true,
        "modalities": {
          "input": [
            "text",
            "image",
            "video"
          ]
        },
        "limit": {
          "context": 262144,
          "output": 262144
        },
        "cost": {
          "input": 0.95,
          "output": 4,
          "cache_read": 0.19
        },
        "temperature": false
      },
      "kimi-k3": {
        "id": "kimi-k3",
        "name": "Kimi K3",
        "reasoning": true,
        "attachment": true,
        "modalities": {
          "input": [
            "text",
            "image",
            "video"
          ]
        },
        "limit": {
          "context": 1048576,
          "output": 131072
        },
        "cost": {
          "input": 3,
          "output": 15,
          "cache_read": 0.3
        },
        "temperature": false,
        "reasoning_options": {
          "effort": [
            "max"
          ]
        }
      },
      "ling-3.0-flash-fin-free": {
        "id": "ling-3.0-flash-fin-free",
        "name": "Ling 3.0 Flash Fin Free",
        "reasoning": true,
        "attachment": false,
        "modalities": {
          "input": [
            "text"
          ]
        },
        "limit": {
          "context": 262144,
          "output": 32768
        },
        "cost": {
          "input": 0,
          "output": 0,
          "cache_read": 0
        },
        "temperature": true
      },
      "longcat-2.5-preview-free": {
        "id": "longcat-2.5-preview-free",
        "name": "LongCat 2.5 Preview Free",
        "reasoning": true,
        "attachment": true,
        "modalities": {
          "input": [
            "text",
            "image"
          ]
        },
        "limit": {
          "context": 1000000,
          "output": 131072
        },
        "cost": {
          "input": 0,
          "output": 0,
          "cache_read": 0
        },
        "temperature": true
      },
      "mimo-v2.5-free": {
        "id": "mimo-v2.5-free",
        "name": "MiMo V2.5 Free",
        "reasoning": true,
        "attachment": true,
        "modalities": {
          "input": [
            "text",
            "image",
            "audio",
            "video"
          ]
        },
        "limit": {
          "context": 200000,
          "output": 32000
        },
        "cost": {
          "input": 0,
          "output": 0,
          "cache_read": 0
        },
        "temperature": true
      },
      "mimo-v2.6-flash-free": {
        "id": "mimo-v2.6-flash-free",
        "name": "MiMo-V2.6-Flash Free",
        "reasoning": true,
        "attachment": true,
        "modalities": {
          "input": [
            "text",
            "image",
            "audio",
            "video"
          ]
        },
        "limit": {
          "context": 200000,
          "output": 32000
        },
        "cost": {
          "input": 0,
          "output": 0,
          "cache_read": 0
        },
        "temperature": true
      },
      "minimax-m2.5": {
        "id": "minimax-m2.5",
        "name": "MiniMax-M2.5",
        "reasoning": true,
        "attachment": false,
        "modalities": {
          "input": [
            "text"
          ]
        },
        "limit": {
          "context": 204800,
          "output": 131072
        },
        "cost": {
          "input": 0.3,
          "output": 1.2,
          "cache_read": 0.06
        },
        "temperature": true
      },
      "minimax-m2.7": {
        "id": "minimax-m2.7",
        "name": "MiniMax-M2.7",
        "reasoning": true,
        "attachment": false,
        "modalities": {
          "input": [
            "text"
          ]
        },
        "limit": {
          "context": 204800,
          "output": 131072
        },
        "cost": {
          "input": 0.3,
          "output": 1.2,
          "cache_read": 0.06
        },
        "temperature": true
      },
      "minimax-m3": {
        "id": "minimax-m3",
        "name": "MiniMax-M3",
        "reasoning": true,
        "attachment": true,
        "modalities": {
          "input": [
            "text",
            "image",
            "video"
          ]
        },
        "limit": {
          "context": 512000,
          "output": 128000
        },
        "cost": {
          "input": 0.3,
          "output": 1.2,
          "cache_read": 0.06
        },
        "temperature": true
      },
      "muse-spark-1.2": {
        "id": "muse-spark-1.2",
        "name": "Muse Spark 1.2",
        "reasoning": true,
        "attachment": true,
        "modalities": {
          "input": [
            "text",
            "image",
            "video",
            "pdf",
            "audio"
          ]
        },
        "limit": {
          "context": 1048576,
          "output": 131072
        },
        "cost": {
          "input": 1.25,
          "output": 4.25,
          "cache_read": 0.15
        },
        "temperature": true,
        "reasoning_options": {
          "effort": [
            "minimal",
            "low",
            "medium",
            "high",
            "xhigh"
          ]
        }
      },
      "muse-spark-1.2-contributor-free": {
        "id": "muse-spark-1.2-contributor-free",
        "name": "Muse Spark 1.2 Free",
        "reasoning": true,
        "attachment": true,
        "modalities": {
          "input": [
            "text",
            "image",
            "video",
            "pdf",
            "audio"
          ]
        },
        "limit": {
          "context": 1048576,
          "output": 131072
        },
        "cost": {
          "input": 0,
          "output": 0,
          "cache_read": 0
        },
        "temperature": true,
        "reasoning_options": {
          "effort": [
            "minimal",
            "low",
            "medium",
            "high",
            "xhigh"
          ]
        }
      },
      "muse-spark-1.3": {
        "id": "muse-spark-1.3",
        "name": "Muse Spark 1.3",
        "reasoning": true,
        "attachment": true,
        "modalities": {
          "input": [
            "text",
            "image",
            "video",
            "pdf",
            "audio"
          ]
        },
        "limit": {
          "context": 1048576,
          "output": 131072
        },
        "cost": {
          "input": 1.25,
          "output": 4.25,
          "cache_read": 0.15
        },
        "temperature": true,
        "reasoning_options": {
          "effort": [
            "minimal",
            "low",
            "medium",
            "high",
            "xhigh"
          ]
        }
      },
      "muse-spark-1.3-contributor-free": {
        "id": "muse-spark-1.3-contributor-free",
        "name": "Muse Spark 1.3 Free",
        "reasoning": true,
        "attachment": true,
        "modalities": {
          "input": [
            "text",
            "image",
            "video",
            "pdf",
            "audio"
          ]
        },
        "limit": {
          "context": 1048576,
          "output": 131072
        },
        "cost": {
          "input": 0,
          "output": 0,
          "cache_read": 0
        },
        "temperature": true,
        "reasoning_options": {
          "effort": [
            "minimal",
            "low",
            "medium",
            "high",
            "xhigh"
          ]
        }
      },
      "nemotron-3-ultra-free": {
        "id": "nemotron-3-ultra-free",
        "name": "Nemotron 3 Ultra Free",
        "reasoning": true,
        "attachment": false,
        "modalities": {
          "input": [
            "text"
          ]
        },
        "limit": {
          "context": 1000000,
          "output": 128000
        },
        "cost": {
          "input": 0,
          "output": 0,
          "cache_read": 0
        },
        "temperature": true
      },
      "nemotron-3.5-lightning-free": {
        "id": "nemotron-3.5-lightning-free",
        "name": "Nemotron 3.5 Lightning Free",
        "reasoning": true,
        "attachment": false,
        "modalities": {
          "input": [
            "text"
          ]
        },
        "limit": {
          "context": 262144,
          "output": 262144
        },
        "cost": {
          "input": 0,
          "output": 0,
          "cache_read": 0
        },
        "temperature": true
      },
      "qwen3.5-plus": {
        "id": "qwen3.5-plus",
        "name": "Qwen3.5 Plus",
        "reasoning": true,
        "attachment": true,
        "modalities": {
          "input": [
            "text",
            "image",
            "video"
          ]
        },
        "limit": {
          "context": 262144,
          "output": 65536
        },
        "cost": {
          "input": 0.2,
          "output": 1.2,
          "cache_read": 0.02
        },
        "temperature": true
      },
      "qwen3.6-plus": {
        "id": "qwen3.6-plus",
        "name": "Qwen3.6 Plus",
        "reasoning": true,
        "attachment": true,
        "modalities": {
          "input": [
            "text",
            "image",
            "video"
          ]
        },
        "limit": {
          "context": 262144,
          "output": 65536
        },
        "cost": {
          "input": 0.5,
          "output": 3,
          "cache_read": 0.05
        },
        "temperature": true
      },
      "qwen3.8-flash": {
        "id": "qwen3.8-flash",
        "name": "Qwen3.8 Flash",
        "reasoning": true,
        "attachment": true,
        "modalities": {
          "input": [
            "text",
            "image",
            "video"
          ]
        },
        "limit": {
          "context": 1000000,
          "output": 131072
        },
        "cost": {
          "input": 0.15,
          "output": 0.47,
          "cache_read": 0.016
        },
        "temperature": true,
        "reasoning_options": {
          "effort": [
            "low",
            "medium",
            "xhigh"
          ]
        }
      },
      "qwen3.8-max": {
        "id": "qwen3.8-max",
        "name": "Qwen3.8 Max",
        "reasoning": true,
        "attachment": true,
        "modalities": {
          "input": [
            "text",
            "image"
          ]
        },
        "limit": {
          "context": 262144,
          "output": 131072
        },
        "cost": {
          "input": 2,
          "output": 6,
          "cache_read": 0.25
        },
        "temperature": true
      },
      "space-bunny-free": {
        "id": "space-bunny-free",
        "name": "Space Bunny Free",
        "reasoning": true,
        "attachment": true,
        "modalities": {
          "input": [
            "text",
            "image",
            "video"
          ]
        },
        "limit": {
          "context": 1048576,
          "output": 524288
        },
        "cost": {
          "input": 0,
          "output": 0,
          "cache_read": 0
        },
        "reasoning_options": {
          "effort": [
            "low",
            "medium",
            "high",
            "xhigh",
            "max"
          ]
        }
      }
    },
    "fallback": []
  },
  "opencode-go": {
    "roster": [
      "deepseek-flash",
      "deepseek-v4-flash",
      "deepseek-v4-flash-vision-exp",
      "deepseek-v4-pro",
      "deepseek-v4.1-flash",
      "glm-5",
      "glm-5.1",
      "glm-5.2",
      "glm-5.3",
      "glm-5.3-flash",
      "gpt-5.6-luna",
      "gpt-6-luna",
      "grok-4.5",
      "grok-4.6",
      "grok-4.7",
      "hy3",
      "hy3-preview",
      "hy4-preview",
      "kimi-k2.5",
      "kimi-k2.6",
      "kimi-k2.7-code",
      "kimi-k3",
      "longcat-2.0",
      "longcat-2.5-preview-free",
      "mimo-v2-omni",
      "mimo-v2-pro",
      "mimo-v2.5",
      "mimo-v2.5-pro",
      "mimo-v2.6-flash",
      "mimo-v2.6-pro",
      "minimax-m2.5",
      "minimax-m2.7",
      "minimax-m3",
      "muse-spark-1.2-contributor",
      "muse-spark-1.3-contributor",
      "omen-alpha",
      "qwen3.5-plus",
      "qwen3.6-plus",
      "qwen3.7-max",
      "qwen3.7-plus",
      "qwen3.8-flash",
      "qwen3.8-max",
      "space-bunny-free"
    ],
    "entries": {
      "deepseek-v4-flash": {
        "id": "deepseek-v4-flash",
        "name": "DeepSeek V4 Flash",
        "reasoning": true,
        "attachment": false,
        "modalities": {
          "input": [
            "text"
          ]
        },
        "limit": {
          "context": 1000000,
          "output": 384000
        },
        "cost": {
          "input": 0.15,
          "output": 0.6,
          "cache_read": 0.003
        },
        "temperature": true,
        "reasoning_options": {
          "effort": [
            "low",
            "high",
            "max"
          ]
        }
      },
      "deepseek-v4-flash-vision-exp": {
        "id": "deepseek-v4-flash-vision-exp",
        "name": "DeepSeek V4 Flash Vision Exp",
        "reasoning": true,
        "attachment": true,
        "modalities": {
          "input": [
            "text",
            "image"
          ]
        },
        "limit": {
          "context": 1000000,
          "output": 384000
        },
        "cost": {
          "input": 0.15,
          "output": 0.6,
          "cache_read": 0.003
        },
        "temperature": true,
        "reasoning_options": {
          "effort": [
            "low",
            "high",
            "max"
          ]
        }
      },
      "deepseek-v4-pro": {
        "id": "deepseek-v4-pro",
        "name": "DeepSeek V4 Pro (New)",
        "reasoning": true,
        "attachment": false,
        "modalities": {
          "input": [
            "text"
          ]
        },
        "limit": {
          "context": 1000000,
          "output": 384000
        },
        "cost": {
          "input": 0.66,
          "output": 1.98,
          "cache_read": 0.022
        },
        "temperature": true,
        "reasoning_options": {
          "effort": [
            "high",
            "max"
          ]
        }
      },
      "deepseek-v4.1-flash": {
        "id": "deepseek-v4.1-flash",
        "name": "DeepSeek V4.1 Flash",
        "reasoning": true,
        "attachment": true,
        "modalities": {
          "input": [
            "text",
            "image"
          ]
        },
        "limit": {
          "context": 1000000,
          "output": 384000
        },
        "cost": {
          "input": 0.15,
          "output": 0.6,
          "cache_read": 0.003
        },
        "temperature": true,
        "reasoning_options": {
          "effort": [
            "low",
            "high",
            "max"
          ]
        }
      },
      "glm-5": {
        "id": "glm-5",
        "name": "GLM-5",
        "reasoning": true,
        "attachment": false,
        "modalities": {
          "input": [
            "text"
          ]
        },
        "limit": {
          "context": 204800,
          "output": 131072
        },
        "cost": {
          "input": 1,
          "output": 3.2,
          "cache_read": 0.2
        },
        "temperature": true
      },
      "glm-5.1": {
        "id": "glm-5.1",
        "name": "GLM-5.1",
        "reasoning": true,
        "attachment": false,
        "modalities": {
          "input": [
            "text"
          ]
        },
        "limit": {
          "context": 204800,
          "output": 131072
        },
        "cost": {
          "input": 1.4,
          "output": 4.4,
          "cache_read": 0.26
        },
        "temperature": true
      },
      "glm-5.2": {
        "id": "glm-5.2",
        "name": "GLM-5.2",
        "reasoning": true,
        "attachment": false,
        "modalities": {
          "input": [
            "text"
          ]
        },
        "limit": {
          "context": 1000000,
          "output": 131072
        },
        "cost": {
          "input": 1.4,
          "output": 4.4,
          "cache_read": 0.26
        },
        "temperature": true,
        "reasoning_options": {
          "effort": [
            "high",
            "max"
          ]
        }
      },
      "glm-5.3": {
        "id": "glm-5.3",
        "name": "GLM-5.3",
        "reasoning": true,
        "attachment": false,
        "modalities": {
          "input": [
            "text"
          ]
        },
        "limit": {
          "context": 1000000,
          "output": 131072
        },
        "cost": {
          "input": 1.4,
          "output": 4.4,
          "cache_read": 0.26
        },
        "temperature": true,
        "reasoning_options": {
          "effort": [
            "low",
            "high",
            "max"
          ]
        }
      },
      "glm-5.3-flash": {
        "id": "glm-5.3-flash",
        "name": "GLM-5.3-Flash",
        "reasoning": true,
        "attachment": true,
        "modalities": {
          "input": [
            "text",
            "image",
            "video",
            "pdf"
          ]
        },
        "limit": {
          "context": 1000000,
          "output": 131072
        },
        "cost": {
          "input": 0.15,
          "output": 0.5,
          "cache_read": 0.03
        },
        "temperature": true,
        "reasoning_options": {
          "effort": [
            "low",
            "high",
            "max"
          ]
        }
      },
      "gpt-5.6-luna": {
        "id": "gpt-5.6-luna",
        "name": "GPT-5.6 Luna",
        "reasoning": true,
        "attachment": true,
        "modalities": {
          "input": [
            "text",
            "image",
            "pdf"
          ]
        },
        "limit": {
          "context": 1050000,
          "output": 128000
        },
        "cost": {
          "input": 0.2,
          "output": 1.2,
          "cache_read": 0.02
        },
        "temperature": false,
        "reasoning_options": {
          "effort": [
            "none",
            "low",
            "medium",
            "high",
            "xhigh",
            "max"
          ]
        }
      },
      "gpt-6-luna": {
        "id": "gpt-6-luna",
        "name": "GPT-6 Luna",
        "reasoning": true,
        "attachment": true,
        "modalities": {
          "input": [
            "text",
            "image",
            "pdf"
          ]
        },
        "limit": {
          "context": 1050000,
          "output": 128000
        },
        "cost": {
          "input": 0.1,
          "output": 0.5,
          "cache_read": 0.01
        },
        "temperature": false,
        "reasoning_options": {
          "effort": [
            "none",
            "low",
            "medium",
            "high",
            "xhigh",
            "max"
          ]
        }
      },
      "grok-4.5": {
        "id": "grok-4.5",
        "name": "Grok 4.5",
        "reasoning": true,
        "attachment": true,
        "modalities": {
          "input": [
            "text",
            "image"
          ]
        },
        "limit": {
          "context": 500000,
          "output": 500000
        },
        "cost": {
          "input": 2,
          "output": 6,
          "cache_read": 0.3
        },
        "temperature": true,
        "reasoning_options": {
          "effort": [
            "low",
            "medium",
            "high"
          ]
        }
      },
      "grok-4.6": {
        "id": "grok-4.6",
        "name": "Grok 4.6",
        "reasoning": true,
        "attachment": true,
        "modalities": {
          "input": [
            "text",
            "image"
          ]
        },
        "limit": {
          "context": 500000,
          "output": 500000
        },
        "cost": {
          "input": 2,
          "output": 6,
          "cache_read": 0.5
        },
        "temperature": true,
        "reasoning_options": {
          "effort": [
            "low",
            "medium",
            "high",
            "xhigh"
          ]
        }
      },
      "grok-4.7": {
        "id": "grok-4.7",
        "name": "Grok 4.7",
        "reasoning": true,
        "attachment": true,
        "modalities": {
          "input": [
            "text",
            "image",
            "pdf"
          ]
        },
        "limit": {
          "context": 500000,
          "output": 500000
        },
        "cost": {
          "input": 2,
          "output": 6,
          "cache_read": 0.5
        },
        "temperature": true,
        "reasoning_options": {
          "effort": [
            "low",
            "medium",
            "high",
            "xhigh"
          ]
        }
      },
      "hy3": {
        "id": "hy3",
        "name": "Hy3",
        "reasoning": true,
        "attachment": false,
        "modalities": {
          "input": [
            "text"
          ]
        },
        "limit": {
          "context": 256000,
          "output": 128000
        },
        "cost": {
          "input": 0.14,
          "output": 0.58,
          "cache_read": 0.035
        },
        "temperature": true,
        "reasoning_options": {
          "effort": [
            "none",
            "low",
            "high"
          ]
        }
      },
      "hy4-preview": {
        "id": "hy4-preview",
        "name": "Hy4 preview",
        "reasoning": true,
        "attachment": false,
        "modalities": {
          "input": [
            "text"
          ]
        },
        "limit": {
          "context": 1024000,
          "output": 64000
        },
        "cost": {
          "input": 0.834,
          "output": 2.501,
          "cache_read": 0.042
        },
        "temperature": true,
        "reasoning_options": {
          "effort": [
            "none",
            "high"
          ]
        }
      },
      "kimi-k2.5": {
        "id": "kimi-k2.5",
        "name": "Kimi K2.5",
        "reasoning": true,
        "attachment": true,
        "modalities": {
          "input": [
            "text",
            "image",
            "video"
          ]
        },
        "limit": {
          "context": 262144,
          "output": 65536
        },
        "cost": {
          "input": 0.6,
          "output": 3,
          "cache_read": 0.08
        },
        "temperature": true
      },
      "kimi-k2.6": {
        "id": "kimi-k2.6",
        "name": "Kimi K2.6",
        "reasoning": true,
        "attachment": true,
        "modalities": {
          "input": [
            "text",
            "image",
            "video"
          ]
        },
        "limit": {
          "context": 262144,
          "output": 65536
        },
        "cost": {
          "input": 0.95,
          "output": 4,
          "cache_read": 0.16
        },
        "temperature": true
      },
      "kimi-k2.7-code": {
        "id": "kimi-k2.7-code",
        "name": "Kimi K2.7 Code",
        "reasoning": true,
        "attachment": true,
        "modalities": {
          "input": [
            "text",
            "image",
            "video"
          ]
        },
        "limit": {
          "context": 262144,
          "output": 262144
        },
        "cost": {
          "input": 0.95,
          "output": 4,
          "cache_read": 0.19
        },
        "temperature": false
      },
      "kimi-k3": {
        "id": "kimi-k3",
        "name": "Kimi K3",
        "reasoning": true,
        "attachment": true,
        "modalities": {
          "input": [
            "text",
            "image",
            "video"
          ]
        },
        "limit": {
          "context": 1048576,
          "output": 131072
        },
        "cost": {
          "input": 3,
          "output": 15,
          "cache_read": 0.3
        },
        "temperature": false,
        "reasoning_options": {
          "effort": [
            "max"
          ]
        }
      },
      "longcat-2.0": {
        "id": "longcat-2.0",
        "name": "LongCat-2.0",
        "reasoning": true,
        "attachment": false,
        "modalities": {
          "input": [
            "text"
          ]
        },
        "limit": {
          "context": 1000000,
          "output": 131072
        },
        "cost": {
          "input": 0.3,
          "output": 1.2,
          "cache_read": 0.006
        },
        "temperature": true
      },
      "longcat-2.5-preview-free": {
        "id": "longcat-2.5-preview-free",
        "name": "LongCat 2.5 Preview Free",
        "reasoning": true,
        "attachment": true,
        "modalities": {
          "input": [
            "text",
            "image"
          ]
        },
        "limit": {
          "context": 1000000,
          "output": 131072
        },
        "cost": {
          "input": 0,
          "output": 0,
          "cache_read": 0
        },
        "temperature": true
      },
      "mimo-v2.5": {
        "id": "mimo-v2.5",
        "name": "MiMo V2.5",
        "reasoning": true,
        "attachment": true,
        "modalities": {
          "input": [
            "text",
            "image",
            "audio",
            "video"
          ]
        },
        "limit": {
          "context": 1000000,
          "output": 128000
        },
        "cost": {
          "input": 0.14,
          "output": 0.28,
          "cache_read": 0.0028
        },
        "temperature": true
      },
      "mimo-v2.5-pro": {
        "id": "mimo-v2.5-pro",
        "name": "MiMo V2.5 Pro",
        "reasoning": true,
        "attachment": true,
        "modalities": {
          "input": [
            "text"
          ]
        },
        "limit": {
          "context": 1048576,
          "output": 128000
        },
        "cost": {
          "input": 0.435,
          "output": 0.87,
          "cache_read": 0.003625
        },
        "temperature": true
      },
      "mimo-v2.6-flash": {
        "id": "mimo-v2.6-flash",
        "name": "MiMo-V2.6-Flash",
        "reasoning": true,
        "attachment": true,
        "modalities": {
          "input": [
            "text",
            "image",
            "audio",
            "video"
          ]
        },
        "limit": {
          "context": 1048576,
          "output": 131072
        },
        "cost": {
          "input": 0.14,
          "output": 0.28,
          "cache_read": 0.0028
        },
        "temperature": true
      },
      "mimo-v2.6-pro": {
        "id": "mimo-v2.6-pro",
        "name": "MiMo-V2.6-Pro",
        "reasoning": true,
        "attachment": true,
        "modalities": {
          "input": [
            "text",
            "image",
            "audio",
            "video"
          ]
        },
        "limit": {
          "context": 1048576,
          "output": 131072
        },
        "cost": {
          "input": 0.435,
          "output": 0.87,
          "cache_read": 0.003625
        },
        "temperature": true
      },
      "minimax-m2.5": {
        "id": "minimax-m2.5",
        "name": "MiniMax-M2.5",
        "reasoning": true,
        "attachment": false,
        "modalities": {
          "input": [
            "text"
          ]
        },
        "limit": {
          "context": 204800,
          "output": 131072
        },
        "cost": {
          "input": 0.3,
          "output": 1.2,
          "cache_read": 0.06
        },
        "temperature": true
      },
      "minimax-m2.7": {
        "id": "minimax-m2.7",
        "name": "MiniMax-M2.7",
        "reasoning": true,
        "attachment": false,
        "modalities": {
          "input": [
            "text"
          ]
        },
        "limit": {
          "context": 204800,
          "output": 131072
        },
        "cost": {
          "input": 0.3,
          "output": 1.2,
          "cache_read": 0.06
        },
        "temperature": true
      },
      "minimax-m3": {
        "id": "minimax-m3",
        "name": "MiniMax-M3",
        "reasoning": true,
        "attachment": false,
        "modalities": {
          "input": [
            "text",
            "image",
            "video"
          ]
        },
        "limit": {
          "context": 1000000,
          "output": 131072
        },
        "cost": {
          "input": 0.3,
          "output": 1.2,
          "cache_read": 0.06
        },
        "temperature": true
      },
      "muse-spark-1.2-contributor": {
        "id": "muse-spark-1.2-contributor",
        "name": "Muse Spark 1.2 Contributor",
        "reasoning": true,
        "attachment": true,
        "modalities": {
          "input": [
            "text",
            "image",
            "video",
            "pdf",
            "audio"
          ]
        },
        "limit": {
          "context": 1048576,
          "output": 131072
        },
        "cost": {
          "input": 0.1,
          "output": 0.2,
          "cache_read": 0.002
        },
        "temperature": true,
        "reasoning_options": {
          "effort": [
            "minimal",
            "low",
            "medium",
            "high",
            "xhigh"
          ]
        }
      },
      "muse-spark-1.3-contributor": {
        "id": "muse-spark-1.3-contributor",
        "name": "Muse Spark 1.3 Contributor",
        "reasoning": true,
        "attachment": true,
        "modalities": {
          "input": [
            "text",
            "image",
            "video",
            "pdf",
            "audio"
          ]
        },
        "limit": {
          "context": 1048576,
          "output": 131072
        },
        "cost": {
          "input": 0.1,
          "output": 0.2,
          "cache_read": 0.002
        },
        "temperature": true,
        "reasoning_options": {
          "effort": [
            "minimal",
            "low",
            "medium",
            "high",
            "xhigh"
          ]
        }
      },
      "qwen3.5-plus": {
        "id": "qwen3.5-plus",
        "name": "Qwen3.5 Plus",
        "reasoning": true,
        "attachment": true,
        "modalities": {
          "input": [
            "text",
            "image",
            "video"
          ]
        },
        "limit": {
          "context": 262144,
          "output": 65536
        },
        "cost": {
          "input": 0.2,
          "output": 1.2,
          "cache_read": 0.02
        },
        "temperature": true
      },
      "qwen3.6-plus": {
        "id": "qwen3.6-plus",
        "name": "Qwen3.6 Plus",
        "reasoning": true,
        "attachment": true,
        "modalities": {
          "input": [
            "text",
            "image",
            "video"
          ]
        },
        "limit": {
          "context": 1000000,
          "output": 65536
        },
        "cost": {
          "input": 0.5,
          "output": 3,
          "cache_read": 0.05
        },
        "temperature": true
      },
      "qwen3.7-max": {
        "id": "qwen3.7-max",
        "name": "Qwen3.7 Max",
        "reasoning": true,
        "attachment": false,
        "modalities": {
          "input": [
            "text"
          ]
        },
        "limit": {
          "context": 1000000,
          "output": 65536
        },
        "cost": {
          "input": 2.5,
          "output": 7.5,
          "cache_read": 0.5
        },
        "temperature": true
      },
      "qwen3.7-plus": {
        "id": "qwen3.7-plus",
        "name": "Qwen3.7 Plus",
        "reasoning": true,
        "attachment": true,
        "modalities": {
          "input": [
            "text",
            "image",
            "video"
          ]
        },
        "limit": {
          "context": 1000000,
          "output": 65536
        },
        "cost": {
          "input": 0.4,
          "output": 1.6,
          "cache_read": 0.04
        },
        "temperature": true
      },
      "qwen3.8-flash": {
        "id": "qwen3.8-flash",
        "name": "Qwen3.8 Flash",
        "reasoning": true,
        "attachment": true,
        "modalities": {
          "input": [
            "text",
            "image",
            "video"
          ]
        },
        "limit": {
          "context": 1000000,
          "output": 131072
        },
        "cost": {
          "input": 0.15,
          "output": 0.47,
          "cache_read": 0.016
        },
        "temperature": true,
        "reasoning_options": {
          "effort": [
            "low",
            "medium",
            "xhigh"
          ]
        }
      },
      "qwen3.8-max": {
        "id": "qwen3.8-max",
        "name": "Qwen3.8 Max",
        "reasoning": true,
        "attachment": true,
        "modalities": {
          "input": [
            "text",
            "image",
            "video"
          ]
        },
        "limit": {
          "context": 1000000,
          "output": 131072
        },
        "cost": {
          "input": 2,
          "output": 6,
          "cache_read": 0.25
        },
        "temperature": true,
        "reasoning_options": {
          "effort": [
            "low",
            "medium",
            "xhigh"
          ]
        }
      },
      "space-bunny-free": {
        "id": "space-bunny-free",
        "name": "Space Bunny Free",
        "reasoning": true,
        "attachment": true,
        "modalities": {
          "input": [
            "text",
            "image",
            "video"
          ]
        },
        "limit": {
          "context": 1048576,
          "output": 524288
        },
        "cost": {
          "input": 0,
          "output": 0,
          "cache_read": 0
        },
        "reasoning_options": {
          "effort": [
            "low",
            "medium",
            "high",
            "xhigh",
            "max"
          ]
        }
      }
    },
    "fallback": [
      "deepseek-flash",
      "hy3-preview",
      "mimo-v2-omni",
      "mimo-v2-pro",
      "omen-alpha"
    ]
  }
} as const;
